id: P004578
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:42:34.526536
source_metadata:
  id: bdr:W1KG25213
  title: ཆོས་མངོན་རིན་ཆེན་འདྲེན་པའི་ཤིང་རྟ།
  author: ''
  volumes:
    3b09d28d87a04c55b9ba42e5b8c7452a:
      image_group_id: I1KG25215
      title: ''
      volume_number: 1
      total_pages: 286
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
